export const BASE_PATH = 'http://localhost:3000'
export const SITE_TITLE = 'Freedom Group Rishikesh'
export const SITE_DESC = 'Freedom Group was created by Ajay Das and a group of school friends in 2017 who shared a strong inclination to Serve.'
export const baseURL='/'
export const imgblurDataURL='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mPsqQcAAZ0BDTSBuAQAAAAASUVORK5CYII='
export const HOME_OG_IMAGE_URL ='/images/favicon.png'
